//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumBitLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumBitLib.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array dimensions must agree..
        /// </summary>
        public static string ArrayMatch {
            get {
                return ResourceManager.GetString("ArrayMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows must greater than columns..
        /// </summary>
        public static string Bidiag {
            get {
                return ResourceManager.GetString("Bidiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions of matrices being concatenated are not consistent..
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a Complex number..
        /// </summary>
        public static string CompareTo {
            get {
                return ResourceManager.GetString("CompareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic Failed: Convergence is not reached..
        /// </summary>
        public static string Converge {
            get {
                return ResourceManager.GetString("Converge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can only compute the Cross Product in three dimension..
        /// </summary>
        public static string CrossProd {
            get {
                return ResourceManager.GetString("CrossProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero Polynomial..
        /// </summary>
        public static string Deconv {
            get {
                return ResourceManager.GetString("Deconv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be Hermitian matrix..
        /// </summary>
        public static string Hermitian {
            get {
                return ResourceManager.GetString("Hermitian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be square..
        /// </summary>
        public static string IsSquare {
            get {
                return ResourceManager.GetString("IsSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be symmetric..
        /// </summary>
        public static string IsSymetric {
            get {
                return ResourceManager.GetString("IsSymetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be tridiagonal..
        /// </summary>
        public static string IsTridiag {
            get {
                return ResourceManager.GetString("IsTridiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LU decomposition whithout pivoting does not exist!.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows and columns must be a positive integer number..
        /// </summary>
        public static string MatrixCtor {
            get {
                return ResourceManager.GetString("MatrixCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions must be consistent with the elements number..
        /// </summary>
        public static string MatrixCtor1 {
            get {
                return ResourceManager.GetString("MatrixCtor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size must be a positive integer number..
        /// </summary>
        public static string MatrixCtor2 {
            get {
                return ResourceManager.GetString("MatrixCtor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree..
        /// </summary>
        public static string MatrixMatch {
            get {
                return ResourceManager.GetString("MatrixMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner matrix dimensions must agree..
        /// </summary>
        public static string MatrixMul {
            get {
                return ResourceManager.GetString("MatrixMul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combinatorial number: Cnk,which k must be an integer between 0 and n..
        /// </summary>
        public static string Nchoosek {
            get {
                return ResourceManager.GetString("Nchoosek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be a nonnegative integer..
        /// </summary>
        public static string NonNegInt {
            get {
                return ResourceManager.GetString("NonNegInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments: p=1 or  2, &apos;I&apos;, &apos;F&apos;..
        /// </summary>
        public static string Norm {
            get {
                return ResourceManager.GetString("Norm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n-th derivative,which n must be a nonnegative number..
        /// </summary>
        public static string Polyder {
            get {
                return ResourceManager.GetString("Polyder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be positive definite..
        /// </summary>
        public static string PosDef {
            get {
                return ResourceManager.GetString("PosDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be positive integer..
        /// </summary>
        public static string PosInt {
            get {
                return ResourceManager.GetString("PosInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relaxation factor w must be: 0&lt;w&lt;2..
        /// </summary>
        public static string RelFac {
            get {
                return ResourceManager.GetString("RelFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty matrix: 0-by-1.
        /// </summary>
        public static string Roots {
            get {
                return ResourceManager.GetString("Roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix is badly scaled or nearly singular!.
        /// </summary>
        public static string Singular {
            get {
                return ResourceManager.GetString("Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix dimensions must agree..
        /// </summary>
        public static string Solve {
            get {
                return ResourceManager.GetString("Solve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument: mode must be 1 or 2..
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
    }
}
